language: go

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/net/html
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
script:
 - go test -v ./...
 - echo "mode: command" &gt; overalls.coverprofile
 - for dir in */; do overalls -project=github.com/ysohta/gopl-ex/$dir; grep github $dir/overalls.coverprofile >> overalls.coverprofile ; done
 - goveralls -coverprofile=overalls.coverprofile -repotoken $TOKEN_COVERALLS
