language: go

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/net/html
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
script:
 - go test -v ./...
 
